# https://taskfile.dev

version: '3'
interval: '200ms'

tasks:
# top level task targets

  build-bin:
    sources:
      - ./**/*.go
    generates:
      - bunny-macos
      - bunny-linux
    cmds:
      # - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -gcflags="all=-N -l" -o bunny-macos ./
      - CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -gcflags="all=-N -l" -o bunny-macos ./
      # - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -o bunny-linux ./
      - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -gcflags="all=-N -l" -o bunny-linux ./

  run-bin:
    deps: [build-bin]
    env:
      BUNNY_CONFIG_FILE_PATH: "{{.ROOT_DIR}}/deploy/local/bunny.yaml"
      LOG_HANDLER: text
      LOG_LEVEL: debug
      TZ: UTC
    cmds:
      - cmd: ./bunny-macos
        platforms: [darwin]
      - cmd: ./bunny-linux
        platforms: [linux]


  build-docker-image:
    deps: [build-bin, configure-docker]
    sources:
      - "{{.ROOT_DIR}}/bunny"
      - "{{.ROOT_DIR}}/deploy/containers/bunny/Dockerfile"
    status:
      - docker image inspect bunny:latest
    dir: ./deploy/containers/bunny/
    cmds:
      - cp "{{.ROOT_DIR}}/bunny-linux" "{{.ROOT_DIR}}/deploy/containers/bunny/bunny"
      - defer: rm "{{.ROOT_DIR}}/deploy/containers/bunny/bunny"
      - docker build -t bunny .

  # this is a little hack-ish as there's no way to set memory in docker-desktop.yaml
  # and it isn't returned when getting the cluster JSON
  configure-docker:
    cmds:
      - ctlptl apply -f deploy/ctlptl/docker-desktop.yaml
      - ctlptl docker-desktop set vm.resources.memoryMiB 8192
      # - ctlptl docker-desktop set vm.kubernetes.enabled true
    status:
      - ctlptl get cluster docker-desktop -o json | jq --exit-status '.status.cpus == 4'

  add-telepresence-helm-repo:
    cmds:
      - helm repo add datawire https://app.getambassador.io
    status:
      - helm repo list --output json | jq --exit-status '.[] | select(.name == "datawire")'

  install-telepresence:
    deps: [configure-docker, add-telepresence-helm-repo]
    cmds:
      - helm repo update
      - helm install traffic-manager datawire/telepresence --wait --create-namespace --namespace ambassador 
      - kubectl wait --for=jsonpath='{.status.loadBalancer}' --namespace ambassador service/traffic-manager
    status:
      - helm list --namespace ambassador --output json | jq --exit-status '.[] | select(.name == "traffic-manager")'

  connect-telepresence:
    deps: [install-telepresence]
    cmds:
      - telepresence connect
    status:
      - telepresence status --output json | jq --exit-status '.root_daemon.running'
      - telepresence status --output json | jq --exit-status '.user_daemon.running'
      - telepresence status --output json | jq --exit-status '.user_daemon.status == "Connected"'

  disconnect-telepresence:
    cmds:
      - telepresence quit

  start-telepresence-intercept:
    deps: [connect-telepresence, create-bunny-deployment, create-bunny-secret, create-bunny-service]
    cmds:
      - telepresence intercept bunny --port 1312:1312 --env-file "{{.ROOT_DIR}}/deploy/bunny/kubernetes/bunny.telepresence-env"
    status:
      - telepresence status --output json | jq --exit-status '.root_daemon.running'
      - telepresence status --output json | jq --exit-status '.user_daemon.running'
      - telepresence status --output json | jq --exit-status '.user_daemon.status == "Connected"'

  stop-telepresence-intercept:
    cmds:
      - telepresence leave bunny

  create-bunny-deployment:
    deps: [configure-docker, build-docker-image]
    cmds:
      - kubectl apply -f "{{.ROOT_DIR}}/deploy/kubernetes/bunny/bunny-deployment.yaml"
    status:
      - kubectl get deployment bunny

  create-bunny-secret:
    deps: [configure-docker]
    cmds:
      - kubectl apply -f "{{.ROOT_DIR}}/deploy/kubernetes/bunny/bunny-secret.yaml"
    status:
      - kubectl get secret bunny

  create-bunny-service:
    deps: [configure-docker]
    cmds:
      - kubectl apply -f "{{.ROOT_DIR}}/deploy/kubernetes/bunny/bunny-service.yaml"
    status:
      - kubectl get service bunny

  add-grafana-helm-repo:
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts
    status:
      - helm repo list --output json | jq --exit-status '.[] | select(.name == "grafana")'

  install-grafana:
    deps: [configure-docker, add-grafana-helm-repo, install-mimir, install-tempo]
    cmds:
      - helm repo update
      - helm install grafana grafana/grafana --wait --create-namespace --namespace grafana --version 7.0.19 --values "{{.ROOT_DIR}}/deploy/kubernetes/grafana/grafana-values.yaml"
    status:
      - helm list --namespace grafana --output json | jq --exit-status '.[] | select(.name == "grafana")'

  install-mimir:
    deps: [configure-docker, add-grafana-helm-repo]
    cmds:
      - helm install mimir grafana/mimir-distributed --wait --create-namespace --namespace mimir --version 5.1.4 --values "{{.ROOT_DIR}}/deploy/kubernetes/grafana/mimir-values.yaml"
    status:
      - helm list --namespace mimir --output json | jq --exit-status '.[] | select(.name == "mirir")'

  install-tempo:
    deps: [configure-docker, add-grafana-helm-repo]
    cmds:
      - helm install tempo grafana/tempo-distributed --wait --create-namespace --namespace tempo --version 1.7.3 --values "{{.ROOT_DIR}}/deploy/kubernetes/grafana/tempo-values.yaml"
    status:
      - helm list --namespace tempo --output json | jq --exit-status '.[] | select(.name == "tempo")'

  run-otelcol:
    cmds:
      - otelcol --config="{{.ROOT_DIR}}/deploy/local/otelcol.yaml"