egress:
  initialDelayMilliseconds: 0
  periodMilliseconds: 3000
  timeoutMilliseconds: 2000
  #  TODO-LOW: docs on how to create liveness, readiness, and startup probe equivalents
  # make sure to update README.md (in both the "Pod Spec" and "Config File" sections)
  probes:
    - name: "alpha"
      httpGet:
        # TODO-LOW: we should add support for TLS with self-signed certs
        # we should support checking against files in a directory or against fingerprints
        # the files can come from volume mounted Secrets
        host: "localhost"
        httpHeaders:
          - name: "x-bunny-test-header-name"
            value: "test-value"
          - name: "x-bunny-test-header-name2"
            value: "test-value2"
        port: 2624
        path: "healthz"
      metrics:
        attempts:
          name: "egress_probe_alpha_attempts"
          enabled: true
          extraLabels:
            - name: "egress_probe_alpha_test_label_name"
              value: "egress_probe_alpha_test_label_value"
        responseTime:
          name: "egress_probe_alpha_response_time"
          enabled: true
          extraLabels: []
    - name: "beta"
      httpGet:
        host: "localhost"
        port: 2624
        path: "healthz"
      metrics:
        attempts:
          name: "egress_probe_beta_attempts"
          enabled: false
          extraLabels:
            - name: "egress_probe_beta_test_label_name"
              value: "egress_probe_beta_test_label_value"
        responseTime:
          name: "egress_probe_beta_response_time"
          enabled: true
ingress:
  httpServer:
    port: 1312
    readTimeoutMilliseconds: 5000
    readHeaderTimeoutMilliseconds: 5000
    writeTimeoutMilliseconds: 10000
    idleTimeoutMilliseconds: 2000
    maxHeaderBytes: 10000
    openTelemetryMetricsPath: "otel-metrics"
    prometheusMetricsPath: "prom-metrics"
    # TODO-LOW: update README.md (in both the "Pod Spec" and "Config File" sections) on how this block works
    # TODO-HIGH: the ingress metrics don't seem to be working
    # there's inconsistent naming and some don't show up
    health:
      - path: "healthz-liveness"
        instantQuery:
          timeout: "5s"
          relativeInstantTime: "-5s"
          query: "1.0 >= bool 0.2"
        metrics:
          attempts:
            name: "ingress_healthz_liveness_attempts"
            enabled: true
            extraLabels:
              - name: "ingress_healthz_liveness_attempts_label_name"
                value: "ingress_healthz_liveness_attempts_label_value"
          responseTime:
            name: "ingress_healthz_liveness_response_time"
            enabled: true
            extraLabels: []
      - path: "healthz-readiness"
        rangeQuery:
          timeout: "5s"
          relativeStartTime: "-5s"
          relativeEndTime: "0s"
          interval: "1s"
          query: "1.0 >= bool 0.2"
        metrics:
          attempts:
            name: "ingress_healthz_readiness_attempts"
            enabled: true
            extraLabels: []
          responseTime:
            name: "ingress_healthz_readiness_response_time"
            enabled: true
            extraLabels: []
signals:
  watchedProcessName: "sleep"