apiVersion: v1
kind: Service
metadata:
  name: bee
spec:
  type: ClusterIP
  ports:
  - name: bee
    port: 6560
    protocol: TCP
    targetPort: 6560
  selector:
    app.kubernetes.io/name: bee
  sessionAffinity: None
